version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  docs-build:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-{{ checksum "requirements.txt" }}  # equivalent to python/load-cache
            - pip-{{ checksum "requirements.txt" }}-console_script
      - python/install-deps
      - python/save-cache
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}-console_script
          paths:
            # `sphinx-build` command is installed in user space
            - /home/circleci/.local/bin/
      - run:
          command: python --version && python3 --version
          name: Show Python versions
      - run:
          command: cd docs && make html && cd -
          name: Build HTML documents
      - persist_to_workspace:
          root: docs/_build
          paths: html
  docs-package:
    docker:
      - image: alpine:3
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          command: |
            mv docs/_build/html python-school-ja
            tar -cjf python-school-ja.tar.bz2 python-school-ja
          name: Create a document package
      - store_artifacts:
          path: python-school-ja.tar.bz2
  docs-publish:
    # Publish HTML documents on GitHub Pages.
    # See the following article for the steps
    # Deploying documentation to GitHub Pages with continuous integration - CircleCI
    # (https://circleci.com/blog/automatically-deploy-private-docker-images-to-aws-ecr/)  docs-deploy:
    docker:
      - image: node:12
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.2.0
            git config user.email "circleci@example.com"
            git config user.name "circleci-build"
      - add_ssh_keys:
          fingerprints:
            - "1f:36:6e:72:55:67:f2:01:a0:22:cf:1d:f1:fe:12:f6"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Publish GiHub Pages" --dist docs/_build/html
workflows:
  main:
    jobs:
      - docs-build
      - docs-package:
          requires:
            - docs-build
      - docs-publish:
          requires:
            - docs-build
          filters:
            branches:
              only: master
