version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default:
      tag: "3.8"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python --version && python3 --version
          name: Show Python versions
      - run:
          command: |
            # `sphinx-build` is installed in user space
            echo "PATH is " $PATH
            ls $HOME/.local $HOME/.local/lib $HOME/.local/lib/python3.8
            cd doc && make html
          name: Build HTML documents

workflows:
  main:
    jobs:
      - build-and-test
