version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - restore_cache:
          keys:
            # - pip-{{ checksum "requirements.txt" }}  # equivalent with python/load-cache
            - pip-{{ checksum "requirements.txt" }}-console_script
      - python/install-deps
      - python/save-cache
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}-console_script
          paths:
            - /home/circleci/.local/bin/
      - run:
          command: python --version && python3 --version
          name: Show Python versions
      - run:
          command: |
            # `sphinx-build` is installed in user space
            echo "PATH is " $PATH
            cd doc && make html
          name: Build HTML documents

workflows:
  main:
    jobs:
      - build
